added anew color of hovered tiles during drag and drop if drop
arnaudframmery/qt-tile-layout pull request #9
Opened 2021-05-31 06:47 UTC by andreasharbo

is possible. Also autoformatted tileLayout.py

2021-05-31 06:50 UTC, andreasharbo commented
This only covers drag and drop. Maybe you can think of a solution for resize in a nother PR 💯

2021-06-01 19:26 UTC, arnaudframmery requested changes
I love the result !

It would be great if you can add a line in the readme about the method `setColorEmptyCheck()` :)

There is just one thing that can be annoying :/
If someone use the method `isAreaEmpty()` just to check if an area of the board is empty, this area will be colored. I see 2 easy solutions for that:

- You can maybe think about a parameter in the `isAreaEmpty()` to trigger coloration
- Or triggering coloration in `__isDropPossible()` in fonction of the `isAreaEmpty()` result (I think personnaly that it's the best option)

Let me know what you think about it :)

2021-06-01 19:26 UTC, arnaudframmery commented on QTileLayout/tileLayout.py
> +        """the tile color during if empty during move"""
Small typo in comment

2021-06-01 19:26 UTC, arnaudframmery commented on QTileLayout/tileLayout.py
> +        self.changeTilesColor('resize')
It should be the 'drag_and_drop' color I think

2021-06-01 20:47 UTC, andreasharbo commented
I have pushed a fix to your comments :)

I decided to add a parameter to `isAreaEmpty` method, that defaults to False. This way no existing implementations are affected by it. Also this way other functions can utilize the coloring without implementing it themselves. 

Fx if we want to color the tiles that we are resizing to, all we have to do is call `isAreaEmpty` during resizing with the parameter color=True.

Let me know if that makes sense to you!

2021-06-02 19:38 UTC, arnaudframmery approved these changes
If it's your last commit I'm okay to merge it 👍

2021-06-02 19:51 UTC, andreasharbo commented
i have no more to add for now :)

2021-06-02 20:01 UTC, arnaudframmery commented
Nice ! I will update pypi package by the end of the week

Thank you for the contribution :)

2021-06-02 20:02 UTC, merged

2021-06-02 21:23 UTC, andreasharbo commented
Sounds great! :)